# mybatis-plus相关配置
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  global-config:
    db-config:
      id-type: auto
      field-strategy: NOT_EMPTY
      db-type: MYSQL
  configuration:
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

repeatSubmit:
  intervalTime: 15
token:
  header: REPEAT-SUBMIT-HEADER

spring:
  application:
    name: CAPOL-AMIS-CONFIG-DEMO
  #定义数据源
  datasource:
    druid:
      amis-demo:
        url: jdbc:mysql://81.68.117.201:3306/db_amis_demo?characterEncoding=utf-8&useSSL=false
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: 123321
        initialSize: 5
        minIdle: 5
        maxActive: 20
        # 配置获取连接等待超时的时间
        maxWait: 60000
        # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
        timeBetweenEvictionRunsMillis: 60000
        # 配置一个连接在池中最小生存的时间，单位是毫秒
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
      qa-biz:
        url: jdbc:mysql://10.1.207.12:3306/db_business?characterEncoding=utf-8&useSSL=false
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: business
        password: business_qa_2021
        initialSize: 5
        minIdle: 5
        maxActive: 20
        # 配置获取连接等待超时的时间
        maxWait: 60000
        # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
        timeBetweenEvictionRunsMillis: 60000
        # 配置一个连接在池中最小生存的时间，单位是毫秒
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false

  redis:
    timeout: 50000
    database: 0
    password: 123321
    jedis:
      pool:
        max-active: 1024
        max-wait: 20000
        max-idle: 200
        min-idle: 10
    sentinel:
      master: mymaster
      nodes: 81.68.117.201:26380,81.68.117.201:26381,81.68.117.201:26382
  rabbitmq:
    host: 81.68.117.201
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    listener:
      simple:
        acknowledge-mode: manual  # 开启手动Ack
        prefetch: 1
        concurrency: 5 # 消费者处理线程数
    template:
      exchange: capol-amis-demo
      default-receive-queue: data-sync
      routing-key: capol-amis-demo
    publisher-confirm-type: correlated # exchange可达
    publisher-returns: true # queue可达

xxl:
  job:
    admin:
      addresses: http://127.0.0.1:8080/xxl-job-admin
      username: admin
      password: 123456
    accessToken: default_token
    executor:
      appname: xxl-job-executor-sample
      address:
      ip:
      port: 9999
      logpath: /data/applogs/xxl-job/jobhandler
      logretentiondays: 30
      jobGroup: 1